[build]
  base = "docs"
  publish = "build"
  command = "echo 'hello'; exit 0;"
  ignore = "node ignore_build.mjs"

 [[redirects]]
      from = "/*"
      to = "https://docs.rwsdk.com"
      status = 301
